// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Choice: typeof import('./src/components/subject/choice/Choice.vue')['default']
    CourseItem: typeof import('./src/components/course-item/src/CourseItem.vue')['default']
    ExamItem: typeof import('./src/components/exam-item/src/ExamItem.vue')['default']
    Judgement: typeof import('./src/components/subject/judgement/Judgement.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutNotify: typeof import('@nutui/nutui-taro')['Notify']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    ShortAnswer: typeof import('./src/components/subject/shortAnswer/ShortAnswer.vue')['default']
    Speech: typeof import('./src/components/subject/speech/Speech.vue')['default']
    SubjectVideo: typeof import('./src/components/subject/video/SubjectVideo.vue')['default']
    WebView: typeof import('./src/components/webview/src/WebView.vue')['default']
  }
}
