export const detail = {
    "id": "967811513282859008",
    "creator": "admin",
    "createDate": 1560939664000,
    "modifier": "preview",
    "modifyDate": 1644246135000,
    "delFlag": 0,
    "tenantCode": "gitee",
    "userId": "596307222997372928",
    "examinationId": "590969316204220416",
    "examinationName": "全国计算机统考练习题10道",
    "type": 2,
    "attention": "练习",
    "startTime": 1650785846000,
    "endTime": 1650785856000,
    "duration": "10秒",
    "totalScore": 50,
    "score": 0.0,
    "status": 0,
    "courseId": "590968789617741824",
    "remark": "全国计算机统考练习题10道",
    "userName": "111",
    "deptName": "123546",
    "inCorrectNumber": 4,
    "correctNumber": 0,
    "submitStatus": 3,
    "answers": [
        {
            "id": "967811513878450177",
            "examRecordId": "967811513282859008",
            "subjectId": "590970743878193152",
            "type": 0,
            "answer": "B",
            "answerType": 1,
            "score": 0.0,
            "subject": {
                "id": "590970743878193152",
                "creator": "admin",
                "modifier": "preview",
                "modifyDate": 1619451563000,
                "delFlag": 0,
                "categoryId": "0",
                "subjectName": "<p>自计算机问世至今已经经历了四个时代，划分时代的主要依据是计算机的_</p>",
                "type": 0,
                "choicesType": 0,
                "score": 5.0,
                "analysis": "<p>无</p>",
                "level": 2,
                "answer": {
                    "id": null,
                    "creator": null,
                    "createDate": null,
                    "modifier": null,
                    "modifyDate": null,
                    "delFlag": 0,
                    
                    "tenantCode": null,
                    "ext": null,
                    "examRecordId": null,
                    "subjectId": null,
                    "type": null,
                    "answer": "D",
                    "answerType": null,
                    "score": null,
                    "markStatus": null,
                    "startTime": null,
                    "endTime": null,
                    "newRecord": true
                },
                "options": [
                    {
                        "id": "590970743911747584",
                        "creator": "admin",
                        "createDate": 1560940005000,
                        "modifier": "admin",
                        "modifyDate": 1619451563000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970743878193152",
                        "optionName": "A",
                        "optionContent": "<p>规模</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590970743911747585",
                        "creator": "admin",
                        "createDate": 1560940005000,
                        "modifier": "admin",
                        "modifyDate": 1619451563000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970743878193152",
                        "optionName": "B",
                        "optionContent": "<p>功能</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590970743911747586",
                        "creator": "admin",
                        "createDate": 1560940005000,
                        "modifier": "admin",
                        "modifyDate": 1619451563000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970743878193152",
                        "optionName": "C",
                        "optionContent": "<p>性能!</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590970743911747587",
                        "creator": "admin",
                        "createDate": 1560940005000,
                        "modifier": "admin",
                        "modifyDate": 1619451563000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970743878193152",
                        "optionName": "D",
                        "optionContent": "构成元件",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "836386006973419520",
                        "creator": "admin",
                        "createDate": 1619451563000,
                        "modifier": "admin",
                        "modifyDate": 1619451563000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970743878193152",
                        "optionName": "E",
                        "optionContent": "<p>aaaa</p>",
                        "right": null,
                        "newRecord": false
                    }
                ],
                "newRecord": false
            },
            "markStatus": 1,
            "startTime": 1650785846000,
            "endTime": 1650785848000,
            "duration": "2秒"
        },
        {
            "id": "967811529749696512",
            "examRecordId": "967811513282859008",
            "subjectId": "590970887432441856",
            "type": 0,
            "answer": "D",
            "answerType": 1,
            "score": 0.0,
            "subject": {
                "id": "590970887432441856",
                "creator": "admin",
                "modifier": "admin",
                "modifyDate": 1560940039000,
                "delFlag": 0,
                "categoryId": "0",
                "subjectName": "第一台计算机是在1946年在美国诞生，该机的英文缩写是_",
                "type": 0,
                "choicesType": 0,
                "score": 5.0,
                "analysis": "<p>无</p>",
                "level": 2,
                "answer": {
                    "id": null,
                    "creator": null,
                    "createDate": null,
                    "modifier": null,
                    "modifyDate": null,
                    "delFlag": 0,
                    
                    "tenantCode": null,
                    "ext": null,
                    "examRecordId": null,
                    "subjectId": null,
                    "type": null,
                    "answer": "A",
                    "answerType": null,
                    "score": null,
                    "markStatus": null,
                    "startTime": null,
                    "endTime": null,
                    "newRecord": true
                },
                "options": [
                    {
                        "id": "590970887457607680",
                        "creator": "admin",
                        "createDate": 1560940039000,
                        "modifier": "admin",
                        "modifyDate": 1560940039000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970887432441856",
                        "optionName": "A",
                        "optionContent": "<p>ENIAC</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590970887457607681",
                        "creator": "admin",
                        "createDate": 1560940039000,
                        "modifier": "admin",
                        "modifyDate": 1560940039000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970887432441856",
                        "optionName": "B",
                        "optionContent": "<p>EDVAC</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590970887457607682",
                        "creator": "admin",
                        "createDate": 1560940039000,
                        "modifier": "admin",
                        "modifyDate": 1560940039000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970887432441856",
                        "optionName": "C",
                        "optionContent": "<p>EDVAE</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590970887457607683",
                        "creator": "admin",
                        "createDate": 1560940039000,
                        "modifier": "admin",
                        "modifyDate": 1560940039000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590970887432441856",
                        "optionName": "D",
                        "optionContent": "MARK",
                        "right": null,
                        "newRecord": false
                    }
                ],
                "newRecord": false
            },
            "markStatus": 1,
            "startTime": 1650785848000,
            "endTime": 1650785850000,
            "duration": "2秒"
        },
        {
            "id": "967811537437855744",
            "examRecordId": "967811513282859008",
            "subjectId": "590971026880466944",
            "type": 0,
            "answer": "B",
            "answerType": 1,
            "score": 0.0,
            "subject": {
                "id": "590971026880466944",
                "creator": "admin",
                "modifier": "admin",
                "modifyDate": 1560940072000,
                "delFlag": 0,
                "categoryId": "0",
                "subjectName": "当前的计算机一般被认为是第四代计算机，它所采用的逻辑元件是_",
                "type": 0,
                "choicesType": 0,
                "score": 5.0,
                "analysis": "无",
                "level": 2,
                "answer": {
                    "id": null,
                    "creator": null,
                    "createDate": null,
                    "modifier": null,
                    "modifyDate": null,
                    "delFlag": 0,
                    
                    "tenantCode": null,
                    "ext": null,
                    "examRecordId": null,
                    "subjectId": null,
                    "type": null,
                    "answer": "C",
                    "answerType": null,
                    "score": null,
                    "markStatus": null,
                    "startTime": null,
                    "endTime": null,
                    "newRecord": true
                },
                "options": [
                    {
                        "id": "590971026893049856",
                        "creator": "admin",
                        "createDate": 1560940072000,
                        "modifier": "admin",
                        "modifyDate": 1560940072000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590971026880466944",
                        "optionName": "A",
                        "optionContent": "<p>集成电路</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590971026901438464",
                        "creator": "admin",
                        "createDate": 1560940072000,
                        "modifier": "admin",
                        "modifyDate": 1560940072000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590971026880466944",
                        "optionName": "B",
                        "optionContent": "<p>晶体管</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590971026901438465",
                        "creator": "admin",
                        "createDate": 1560940072000,
                        "modifier": "admin",
                        "modifyDate": 1560940072000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590971026880466944",
                        "optionName": "C",
                        "optionContent": "<p>大规模集成电路</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590971026901438466",
                        "creator": "admin",
                        "createDate": 1560940072000,
                        "modifier": "admin",
                        "modifyDate": 1560940072000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590971026880466944",
                        "optionName": "D",
                        "optionContent": "电子管",
                        "right": null,
                        "newRecord": false
                    }
                ],
                "newRecord": false
            },
            "markStatus": 1,
            "startTime": 1650785850000,
            "endTime": 1650785852000,
            "duration": "2秒"
        },
        {
            "id": "967811551669129216",
            "examRecordId": "967811513282859008",
            "subjectId": "590971151128334336",
            "type": 0,
            "answer": "D",
            "answerType": 1,
            "score": 0.0,
            "subject": {
                "id": "590971151128334336",
                "creator": "admin",
                "modifier": "admin",
                "modifyDate": 1560940102000,
                "delFlag": 0,
                "categoryId": "0",
                "subjectName": "当前计算机的应用最广泛的领域是_",
                "type": 0,
                "choicesType": 0,
                "score": 5.0,
                "analysis": "无",
                "level": 2,
                "answer": {
                    "id": null,
                    "creator": null,
                    "createDate": null,
                    "modifier": null,
                    "modifyDate": null,
                    "delFlag": 0,
                    
                    "tenantCode": null,
                    "ext": null,
                    "examRecordId": null,
                    "subjectId": null,
                    "type": null,
                    "answer": "C",
                    "answerType": null,
                    "score": null,
                    "markStatus": null,
                    "startTime": null,
                    "endTime": null,
                    "newRecord": true
                },
                "options": [
                    {
                        "id": "590971151170277376",
                        "creator": "admin",
                        "createDate": 1560940102000,
                        "modifier": "admin",
                        "modifyDate": 1560940102000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590971151128334336",
                        "optionName": "A",
                        "optionContent": "<p>辅助设计</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590971151170277377",
                        "creator": "admin",
                        "createDate": 1560940102000,
                        "modifier": "admin",
                        "modifyDate": 1560940102000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590971151128334336",
                        "optionName": "B",
                        "optionContent": "<p>科学计算</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590971151170277378",
                        "creator": "admin",
                        "createDate": 1560940102000,
                        "modifier": "admin",
                        "modifyDate": 1560940102000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590971151128334336",
                        "optionName": "C",
                        "optionContent": "<p>数据处理</p>",
                        "right": null,
                        "newRecord": false
                    },
                    {
                        "id": "590971151170277379",
                        "creator": "admin",
                        "createDate": 1560940102000,
                        "modifier": "admin",
                        "modifyDate": 1560940102000,
                        "delFlag": 0,
                        
                        "tenantCode": "gitee",
                        "ext": null,
                        "subjectChoicesId": "590971151128334336",
                        "optionName": "D",
                        "optionContent": "<p>过程控制</p>",
                        "right": null,
                        "newRecord": false
                    }
                ],
                "newRecord": false
            },
            "markStatus": 1,
            "startTime": 1650785851000,
            "endTime": 1650785855000,
            "duration": "4秒"
        }
    ],
    "newRecord": false
};

export const subject = {

}
